FROM node:18

WORKDIR /app

COPY frontend/ ./frontend

WORKDIR /app/frontend

RUN yarn install --frozen-lockfile

#RUN npx react-native bundle --platform ios --dev false --entry-file index.ts --bundle-output ios/main.jsbundle --assets-dest ios/assets
#RUN npx react-native bundle --platform android --dev false --entry-file index.ts --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

EXPOSE 8080

CMD ["npx", "react-native", "start"]
