version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - database

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

  database:
    image: postgres
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
