name: Detox Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detox-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up MySQL
        uses: devcontainers/features@v0
        with:
          name: mysql

      - name: Start MySQL service
        run: |
          docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=root -d mysql:8

      - name: Create database
        run: |
          docker exec -i mysql-db mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS multilern;"

      - name: Create database from dump
        run: |
          sleep 15  # Czekamy na uruchomienie MySQL
          docker exec -i mysql-db mysql -uroot -proot multilern < backend/helpers/multilern.sql

      - name: Start backend
        run: |
          cd backend
          yarn install
          yarn start &  # Uruchamiamy backend w tle

      - name: Navigate to frontend
        working-directory: frontend
        run: echo "Navigated to frontend folder"

      - name: Install frontend dependencies
        working-directory: frontend
        run: yarn install

      - name: Install iOS dependencies
        if: runner.os == 'macOS'
        working-directory: frontend
        run: |
          brew install cocoapods
          brew install applesimutils
          cd ios && pod install

      - name: Build Detox
        working-directory: frontend
        run: yarn e2e:build-ios-debug

      - name: Run Detox tests
        working-directory: frontend
        run: yarn e2e:test-ios-debug

      - name: Stop MySQL container and backend
        run: |
          docker stop mysql-db
          docker rm mysql-db
          kill $(jobs -p)  # Zatrzymujemy proces backendu
