name: Detox Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  detox-tests:
    runs-on: macos-latest # Używamy macOS, aby uruchomić symulatory iOS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalacja MySQL 8.0
      - name: Install MySQL 8.0
        run: |
          brew install mysql  # Instalacja MySQL (najnowsza wersja 8.0)
          brew services start mysql  # Uruchomienie MySQL jako usługi
          mysql --version  # Sprawdzenie wersji MySQL

      # Oczekiwanie na pełne uruchomienie MySQL
      - name: Wait for MySQL to start
        run: |
          while ! mysqladmin ping --silent; do
            echo "Waiting for MySQL to start..."
            sleep 2
          done

      # Tworzenie bazy danych
      - name: Create database
        run: |
          mysql -uroot -e "CREATE DATABASE IF NOT EXISTS multilern;"  # Tworzenie bazy danych

      # Import bazy danych z pliku dump
      - name: Create database from dump
        run: |
          mysql -uroot multilern < backend/helpers/multilern.sql  # Załadowanie dumpu bazy danych

      # Start backendu
      - name: Start backend
        run: |
          cd backend
          yarn install
          yarn start &  # Uruchamiamy backend w tle

      - name: Navigate to frontend
        working-directory: frontend
        run: echo "Navigated to frontend folder"

      - name: Install frontend dependencies
        working-directory: frontend
        run: yarn install

      - name: Install iOS dependencies
        if: runner.os == 'macOS'
        working-directory: frontend
        run: |
          brew install cocoapods
          brew tap wix/brew
          brew install applesimutils
          cd ios && pod install

      - name: Build Detox
        working-directory: frontend
        run: yarn e2e:build-ios-debug

      - name: Start the app
        working-directory: frontend
        run: |
          yarn ios &  # Uruchomienie aplikacji w tle
          sleep 60  # Czekanie na pełne uruchomienie aplikacji

      - name: Run Detox tests
        working-directory: frontend
        run: yarn e2e:test-ios-debug

      # Zatrzymywanie MySQL i backendu
      - name: Stop MySQL service and backend
        run: |
          brew services stop mysql  # Zatrzymujemy usługę MySQL
          kill $(jobs -p)  # Zatrzymujemy proces backendu
